
BoxLayout:
    orientation: 'vertical'
    spacing: 5
    padding: 5

    TextInput:
        id: display
        text: "0"
        font_size: 48
        halign: 'right'
        valign: 'middle'
        readonly: True
        size_hint_y: 0.2

    GridLayout:
        cols: 4
        spacing: 5

    
        Button:
            text: "7"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "8"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "9"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "/"
            font_size: 24
            on_press: app.actualizar_display(self.text)

   
        Button:
            text: "4"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "5"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "6"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "*"
            font_size: 24
            on_press: app.actualizar_display(self.text)

     
        Button:
            text: "1"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "2"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "3"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "-"
            font_size: 24
            on_press: app.actualizar_display(self.text)

    
        Button:
            text: "C"  # Clear
            font_size: 24
            on_press: app.limpiar_display()
        Button:
            text: "0"
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "."
            font_size: 24
            on_press: app.actualizar_display(self.text)
        Button:
            text: "+"
            font_size: 24
            on_press: app.actualizar_display(self.text)

    Button:
        text: "="
        font_size: 24
        size_hint_y: 0.15
        on_press: app.calcular_resultado()
